<a href="https://colab.research.google.com/github/praneeth1711/B20_1711/blob/main/LAB2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
l=[1,2,3,4,"CSE"]
print(l)
for i in l :
  print(type(i),i)


[1, 2, 3, 4, 'CSE']
<class 'int'> 1
<class 'int'> 2
<class 'int'> 3
<class 'int'> 4
<class 'str'> CSE


In [31]:
l=[10,20,30,40]
l.append(50)
print(l)
l.pop()
print(l)
l.remove(30)
print(l)
l.insert(2,100)
l.sort()
print(sum(l))
print(min(l))
print(max(l))
print(l)

[10, 20, 30, 40, 50]
[10, 20, 30, 40]
[10, 20, 40]
170
10
100
[10, 20, 40, 100]


In [65]:
data = [
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
]
for i in data :
  print(i)



[10, 20, 30]
[40, 50, 60]
[70, 80, 90]
[10, 20, 30] [40, 50, 60] [70, 80, 90]


In [33]:
my_list = [1, 2, 3, 4, 5]

for item in my_list:
  print(item)

1
2
3
4
5


In [40]:
t=(10,20,30,40,50)
print(t)
for i in t:
  print(type(i),i)
if 20 in t :
  print(" is present")
else :
  print(" is not present")

t=(1,2,3,4,2,2)
print(t.count(2))
print(t.index(4))
print(t)

l=[10,20,30]
t=tuple(l)
print(t)

nested_tuple = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 9)
)
print(nested_tuple)



(10, 20, 30, 40, 50)
<class 'int'> 10
<class 'int'> 20
<class 'int'> 30
<class 'int'> 40
<class 'int'> 50
 is present
3
3
(1, 2, 3, 4, 2, 2)
(10, 20, 30)
((1, 2, 3), (4, 5, 6), (7, 8, 9))


In [55]:
student={"name":"java","id":"1711","brach":"cse","batch":"20"}
print(student.keys())
print(student.values())
print(student.items())

for key,value in student.items():
  print(key,":" ,value)


student["college"]="sru"
print(student)
student["specialisation"]="AIML"
print(student)
del student["specialisation"]
print(student)


student1={101:{"name":"c","id":"1"},"102":{"name":"python","id":"2"}}
print(student1)
print(student1[101])
print(student1[101]["name"])



dict_keys(['name', 'id', 'brach', 'batch'])
dict_values(['java', '1711', 'cse', '20'])
dict_items([('name', 'java'), ('id', '1711'), ('brach', 'cse'), ('batch', '20')])
name : java
id : 1711
brach : cse
batch : 20
{'name': 'java', 'id': '1711', 'brach': 'cse', 'batch': '20', 'college': 'sru'}
{'name': 'java', 'id': '1711', 'brach': 'cse', 'batch': '20', 'college': 'sru', 'specialisation': 'AIML'}
{'name': 'java', 'id': '1711', 'brach': 'cse', 'batch': '20', 'college': 'sru'}
{101: {'name': 'c', 'id': '1'}, '102': {'name': 'python', 'id': '2'}}
{'name': 'c', 'id': '1'}
c


In [71]:
s={1,2,3,4}
print(s)
s={1,2,3,4,1,2,3,4}
print(s)
for i in s:
  print(i)
if 2 in s:
  print("found");
else:
  print("not found")


a={1,2,3,4}
b={3,4,5,6}
print("union",a|b)
print("intersection",a&b)
print("difference",a-b)
print("difference",b-a)
print("symmetric difference",a^b)
print(a.union(b))
print(a.intersection(b))
print(a.difference(b))
print(b.difference(a))
print(a.symmetric_difference(b))

p={1,2,3}
p.add(4)
print(p)
p.remove(2)
print(p)
p.clear()
print(p)



{1, 2, 3, 4}
{1, 2, 3, 4}
1
2
3
4
found
union {1, 2, 3, 4, 5, 6}
intersection {3, 4}
difference {1, 2}
difference {5, 6}
symmetric difference {1, 2, 5, 6}
{1, 2, 3, 4, 5, 6}
{3, 4}
{1, 2}
{5, 6}
{1, 2, 5, 6}
{1, 2, 3, 4}
{1, 3, 4}
set()


In [90]:

import numpy as np
marks = np.array([[85, 78, 92], [70, 65, 80],  [90, 88, 94],  [60, 75, 70],  [95, 85, 99] ])
avg_marks = np.mean(marks)
min_marks = np.min(marks)
max_marks = np.max(marks)
print(avg_marks)
print(min_marks)
print(max_marks)

print("Marks of Student 3:", marks[2])
print("Marks of Students 2 to 4: ", marks[1:4])

excellent= marks >80
print(excellent)

each_subject = marks.T
print("EACH SUBJECT MARKS", each_subject)





81.73333333333333
60
99
Marks of Student 3: [90 88 94]
Marks of Students 2 to 4:  [[70 65 80]
 [90 88 94]
 [60 75 70]]
[[ True False  True]
 [False False False]
 [ True  True  True]
 [False False False]
 [ True  True  True]]
EACH SUBJECT MARKS [[85 70 90 60 95]
 [78 65 88 75 85]
 [92 80 94 70 99]]
