<a href="https://colab.research.google.com/github/praneeth1711/B20_1711/blob/main/LAB_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
fp=open("example.text",'w')
fp.write("hello ! im praneeth\n")
fp.write(" this is file hanlding in python\n")
fp.write("python\n")


7

In [ ]:
fp=open("example.text",'r')
information=fp.read()
print("information : ",information)
fp.close()


information :  hello ! im praneeth
 this is file hanlding in python
python



In [ ]:
fp=open("example.text",'r')
line1=fp.readline()
print("line1 : ",line1)
line2=fp.readline()
print("line2: ",line2)
fp.close()

line1 :  hello ! im praneeth

line2:   this is file hanlding in python



In [ ]:
#reading all lines
fp=open("example.text",'r')
lines=fp.readlines()
print("lines : ",lines)
fp.close()

lines :  ['hello ! im praneeth\n', ' this is file hanlding in python\n', 'python\n']


In [ ]:
#appending data to an exsisting file
fp=open("example.text",'a')
fp.write("appending new data.........\n")
fp.close()

In [ ]:
fp=open("example.text",'r')
information=fp.read()
print("information : ",information)
fp.close()

information :  hello ! im praneeth
 this is file hanlding in python
python
appending new data.........



In [ ]:
#using with statement
with open("example.text",'r') as file:
  fp=file.read()
  print("information : ",fp)

information :  hello ! im praneeth
 this is file hanlding in python
python
appending new data.........



In [ ]:
#working with csv files [comma separated values]
import csv
with open("student.csv","w",newline='') as f :
  writer=csv.writer(f)
  writer.writerow(["name","marks"])
  writer.writerow(["alice",90])
  writer.writerow(["bob",80])
  writer.writerow(["charlie",70])
  writer.writerow(["david",60])




In [ ]:
import csv
with open("data.csv","w",newline='') as f :
  writer=csv.writer(f)
  writer.writerows([["name","marks"],["pandu",100],["pottish",99],["hermoine",95],["nancy",69]])


In [ ]:
# reading from csv
with open("student.csv","r") as f :
  reader=csv.reader(f)
  for row in reader:
    print(row)

['name', 'marks']
['alice', '90']
['bob', '80']
['charlie', '70']


In [ ]:
import numpy as np
print("1D array :")
a=np.array([1,2,3,4])
print(a)
print("2D array :")
b=np.array([[1,2,3],[4,5,6]])
print(b)
print("zeros array")
zeros_array=np.zeros((3,3))
print(zeros_array)
print("ones array")
ones_array=np.ones((3,3))
print(ones_array)
print("range of array :")
range_array=np.arange(1,10,2)
print(range_array)
print("random array :")
random_array=np.random.rand(3,3)
print(random_array)

1D array :
[1 2 3 4]
2D array :
[[1 2 3]
 [4 5 6]]
zeros array
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
range of array :
[1 3 5 7 9]
random array :
[[0.73387473 0.25599649 0.20149473]
 [0.24490811 0.14716334 0.73092618]
 [0.59860065 0.02358575 0.22494521]]


In [ ]:
# array attributes
a=np.array([[1,2,3],[4,5,6]])
print("shape of array : ",a.shape)
print("size of array : ",a.size)
print("data type of array : ",a.dtype)
print("dimension : ",a.ndim)
print("item size : ",a.itemsize)

shape of array :  (2, 3)
size of array :  6
data type of array :  int64
dimension :  2
item size :  8


In [ ]:
#indexing and slicing
a=np.array([1,2,3,4,5,6])
print("first element : ",a[0])
print("last element : ",a[-1])
print("slice[1,:4]",a[1:4])
a=np.array([[1,2,3],[4,5,6]])
print("first row : ",a[0])
print("second row : ",a[1])
print("first element : ",a[0][0])
print("second column :",a[1, :])
print("element at row1, col2 : ",arr[0,1])

first element :  1
last element :  6
slice[1,:4] [2 3 4]
first row :  [1 2 3]
second row :  [4 5 6]
first element :  1
second column : [4 5 6]
element at row1, col2 :  2


In [ ]:
#arrayb operations

a=np.array([1,2,3])
b=np.array([4,5,6])

print("Additon : ",a+b)
print("Subtraction : ",a-b)
print("Multiplication : ",a*b)
print("Division : ",a/b)
print("power : ",a**2)



Additon :  [5 7 9]
Subtraction :  [-3 -3 -3]
Multiplication :  [ 4 10 18]
Division :  [0.25 0.4  0.5 ]
power :  [1 4 9]


In [ ]:
#mathematical functions
a=np.array([0,np.pi/2,np.pi])
print("sine",np.sin(a))
print("cosine",np.cos(a))
print("sqaure root",np.sqrt([1,4,9]))
print("exponential",np.exp([1,2]))

sine [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cosine [ 1.000000e+00  6.123234e-17 -1.000000e+00]
sqaure root [1. 2. 3.]
exponential [2.71828183 7.3890561 ]


In [ ]:
#aggregate functions
arr=np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Sum:",np.sum(arr))
print("Min:",np.min(arr))
print("Max:",np.max(arr))
print("Mean:",np.mean(arr))
print("Median:",np.median(arr))
print("Standard Deviation:",np.std(arr))
print("Sum along axis 0:",np.sum(arr,axis=0)) #column wise sum
print("Sum along axis 1:",np.sum(arr,axis=1)) #row wise sum

Array:
 [[1 2 3]
 [4 5 6]]
Sum: 21
Min: 1
Max: 6
Mean: 3.5
Median: 3.5
Standard Deviation: 1.707825127659933
Sum along axis 0: [5 7 9]
Sum along axis 1: [ 6 15]


In [ ]:
#broadcasting
a=np.array([1,2,3])
b=5
print("add scalar to array ",a+b)

c=np.array([[1],[2],[3]])
d=np.array([1,2,3])
print("broadcasting sum : ",c+d)

add scalar to array  [6 7 8]
broadcasting sum :  [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
#Matrix Operations
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("Matrix Multiplication:\n",np.dot(A,B))
print("Matrix Transpose:\n",A.T)
print("Matrix Transpose:\n",B.T)
print("Matrix Inverse:\n",np.linalg.inv(A))
print("Matrix Determinant:\n",np.linalg.det(A))

Matrix Multiplication:
 [[19 22]
 [43 50]]
Matrix Transpose:
 [[1 3]
 [2 4]]
Matrix Transpose:
 [[5 7]
 [6 8]]
Matrix Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Matrix Determinant:
 -2.0000000000000004


In [ ]:
#Sample Program - Student Analsis
import numpy as np
# Marks of students in 3 subjects
marks = np.array([
[85, 90, 88],
[78, 81, 85],
[92, 89, 95]
])
print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks, axis=0))

Average marks per student: [87.66666667 81.33333333 92.        ]
Average marks per subject: [85.         86.66666667 89.33333333]
Highest marks in each subject: [92 90 95]
Lowest marks in each subject: [78 81 85]


In [2]:
import numpy as np
A = np.array([[1, -2, 3],
              [4, -5, 6],
              [7,  8, -9]])

print(" Original Array:\n", A)
A_squared = A ** 2
print("Squared Array:\n", A_squared)

A_sqrt = np.sqrt(A_squared)
print("Square Root of Squared Array:\n", A_sqrt)
A_nonneg = np.where(A < 0, 0, A)
print("Negatives replaced with 0:\n", A_nonneg)
count_greater_5 = np.sum(A > 5)
print("Number of elements > 5:", count_greater_5)
count_even = np.sum(A % 2 == 0)
print("Number of even elements:", count_even)
mask = A > 3
print("Boolean Mask of elements > 3:\n", mask)
masked_result = np.where(mask, A, -1)
print("Masked Result (values > 3, else -1):\n", masked_result)


 Original Array:
 [[ 1 -2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
Squared Array:
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Square Root of Squared Array:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Negatives replaced with 0:
 [[1 0 3]
 [4 0 6]
 [7 8 0]]
Number of elements > 5: 3
Number of even elements: 4
Boolean Mask of elements > 3:
 [[False False False]
 [ True False  True]
 [ True  True False]]
Masked Result (values > 3, else -1):
 [[-1 -1 -1]
 [ 4 -1  6]
 [ 7  8 -1]]
